<?php

namespace ResumeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Cache;

/**
 * experienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class experienceRepository extends EntityRepository
{
    public function findValid() {
        $q = $this->_em->createQueryBuilder()
            ->select('e')
            ->from($this->_entityName, 'e')
            ->andWhere('e.status = 1')
            ->orderBy('e.order', 'ASC')
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
        ;

        return $q->getResult();
    }
}
