<?php

namespace ResumeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Cache;

/**
 * paramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paramRepository extends EntityRepository
{
    public function findAllWithKey() {
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p', 'p.type')
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true)
        ;

        return $qb->getResult();
    }
}
